"""
Student information for this assignment:

Replace <FULL NAME> with your name.
On my/our honor, NOAH YU and SAMUEL SUH, this
programming assignment is my own work and I have not provided this code to
any other student.

I have read and understand the course syllabus's guidelines regarding Academic
Integrity. I understand that if I violate the Academic Integrity policy (e.g.
copy code from someone else, have the code generated by an LLM, or give my
code to someone else), the case shall be submitted to the Office of the Dean of
Students. Academic penalties up to and including an F in the course are likely.

UT EID 1: ny3259
UT EID 2:
"""

# SAM: all methods done but having trouble with access. help por favor also add ur eid

from abc import ABC, abstractmethod
import random

DAILY_EXPENSE = 60
HAPPINESS_THRESHOLD = 50
MANAGER_BONUS = 1000
TEMP_EMPLOYEE_PERFORMANCE_THRESHOLD = 50
PERM_EMPLOYEE_PERFORMANCE_THRESHOLD = 25
RELATIONSHIP_THRESHOLD = 10
INITIAL_PERFORMANCE = 75
INITIAL_HAPPINESS = 50
PERCENTAGE_MAX = 100
PERCENTAGE_MIN = 0
SALARY_ERROR_MESSAGE = "Salary must be non-negative."


# TODO: implement this class. You may delete this comment when you are done.
class Employee(ABC):
    """
    Abstract base class representing a generic employee in the system.
    """

    def __init__(self, name, manager, salary, savings):
        self.relationships = {}
        self.savings = savings
        self.is_employed = True
        self.__name = name
        self.__manager = manager
        self.performance = INITIAL_PERFORMANCE
        self.happiness = INITIAL_HAPPINESS
        self.salary = salary

    @property  # idk if we have to write setter methods
    def name(self):
        return self.__name

    @property  # for some reason, the other non-employee classes cannot access their methods or
    def manager(self):
        return self.__manager

    @abstractmethod
    def work(self):
        pass

    def interact(self, other):
        if other.name not in self.relationships:
            self.relationships[other.name] = 0
        elif self.relationships[other.name] >= RELATIONSHIP_THRESHOLD:
            self.relationships[other.name] += 1
        elif (
            self.happiness >= HAPPINESS_THRESHOLD
            and other.happiness >= HAPPINESS_THRESHOLD
        ):
            self.relationships[other.name] += 1
        else:
            self.relationships[other.name] -= 1
            self.happiness -= 1

    def daily_expense(self):
        self.happiness -= 1
        self.savings -= DAILY_EXPENSE

    def __str__(self):
        return f"{self.name}\n\tSalary: ${self.salary}\n\tSavings: ${self.savings}\n\tHappiness: %{self.happiness}\n\tPerformance: %{self.performance}"


# TODO: implement this class. You may delete this comment when you are done.
class Manager(Employee):
    """
    A subclass of Employee representing a manager.
    """

    def work(self):
        performance_change = random.randint(-5, 5)
        self.performance += performance_change
        if performance_change <= 0:
            self.happiness -= 1
            for emps in self.relationships.keys():
                self.relationships[emps] -= 1
        else:
            self.happiness += 1


# TODO: implement this class. You may delete this comment when you are done.
class TemporaryEmployee(Employee):
    """
    A subclass of Employee representing a temporary employee.
    """

    def work(self):
        performance_change = random.randint(-15, 15)
        self.performance += performance_change
        if performance_change <= 0:
            self.happiness -= 2
        else:
            self.happiness += 1

    def interact(self, other):
        super().interact(other)
        if type(other) == Manager:
            if (
                other.happiness >= HAPPINESS_THRESHOLD
                and self.performance >= TEMP_EMPLOYEE_PERFORMANCE_THRESHOLD
            ):
                self.savings += MANAGER_BONUS
            elif other.happiness <= HAPPINESS_THRESHOLD:
                self.salary = self.salary / 2
                self.happiness -= 5  # add if salary negative?


# TODO: implement this class. You may delete this comment when you are done.
class PermanentEmployee(Employee):
    """
    A subclass of Employee representing a permanent employee.
    """

    def work(self):
        performance_change = random.randint(-10, 10)
        self.performance += performance_change
        if performance_change >= 0:
            self.happiness += 1

    def interact(self, other):
        super().interact(other)
        if type(other) == Manager:
            if (
                other.happiness >= HAPPINESS_THRESHOLD
                and self.performance >= PERM_EMPLOYEE_PERFORMANCE_THRESHOLD
            ):
                self.savings += MANAGER_BONUS
            elif other.happiness <= HAPPINESS_THRESHOLD:
                self.happiness -= 1
